/* ============================================================
   KICKS ON DECK — self-host the web fonts
   ------------------------------------------------------------
   Downloads the Google Fonts CSS the site uses (Chrome UA -> woff2), keeps
   the latin subset, saves the files under assets/fonts/ and writes
   assets/fonts/fonts.css with local URLs + font-display: swap.

   Why: one fewer third-party DNS/TLS hop on every page view, no dependency
   on fonts.googleapis.com at render time (the covers renderer and CI
   screenshots need the real faces), and a preloadable display font.

     node scripts/fonts/vendor.mjs      # needs network; run in CI or locally
   Re-run whenever the family list in scripts/build.mjs FONT_HREF changes.
   ============================================================ */
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const OUT = path.join(ROOT, "assets", "fonts");
const CSS_URL = "https://fonts.googleapis.com/css2?family=Archivo:wdth,wght@125,600;125,700;125,800;125,900&family=Hanken+Grotesk:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;700&display=swap";
const UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36";

const res = await fetch(CSS_URL, { headers: { "User-Agent": UA } });
if (!res.ok) throw new Error("fonts css " + res.status);
const css = await res.text();

// Blocks look like: /* latin */ @font-face { font-family: 'Archivo'; font-style: normal; font-weight: 800; font-stretch: 125%; src: url(https://…) format('woff2'); unicode-range: … }
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
fs.mkdirSync(OUT, { recursive: true });
let out = "/* Self-hosted web fonts (OFL). Generated by scripts/fonts/vendor.mjs — do not edit by hand. */\n";
const seen = new Set();
for (const [, subset, block] of blocks) {
  if (subset !== "latin") continue; // english storefront; latin-ext/vietnamese/cyrillic never render
  const family = block.match(/font-family:\s*'([^']+)'/)[1];
  const weight = block.match(/font-weight:\s*(\d+)/)[1];
  const stretch = (block.match(/font-stretch:\s*(\d+)%/) || [])[1];
  const url = block.match(/url\((https:[^)]+)\)/)[1];
  const name = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight}${stretch ? "-w" + stretch : ""}.woff2`;
  if (seen.has(name)) continue; seen.add(name);
  const r = await fetch(url, { headers: { "User-Agent": UA } });
  if (!r.ok) throw new Error("font file " + r.status + " " + url);
  fs.writeFileSync(path.join(OUT, name), Buffer.from(await r.arrayBuffer()));
  out += "\n" + block.replace(url, `/assets/fonts/${name}`).replace(/\s+/g, " ").replace("@font-face {", "@font-face { font-display: swap;") + "\n";
  console.log("  " + name);
}
fs.writeFileSync(path.join(OUT, "fonts.css"), out);
console.log(`fonts: ${seen.size} files -> assets/fonts/fonts.css`);
